import React from "react";
import Providers from "@/app/components/providers";

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
    viewport: 'width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0'
}

export default function RootLayout({children}: {
    children: React.ReactNode
}) {
    return (
        <html lang="en">
        <body>
            <Providers>
                {children}
            </Providers>
        </body>
        </html>
    )
}
