import React from "react";
import Providers from "../providers";
import {notFound} from "next/navigation";
import {NextIntlClientProvider} from "next-intl";
export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
    viewport: 'width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0'
}

export function generateStaticParams() {
    return [{locale: 'en'}, {locale: 'fr'}];
}

export default async function RootLayout({children, params: {locale}}: {
    children: React.ReactNode,
    params: {
        locale: string
    }
}) {
    let messages;

    try {
        messages = (await import('../../messages/' + locale + '.json')).default;
    } catch (error) {
        notFound();
    }

    return (
        <html lang={locale}>
        <body>
            <NextIntlClientProvider locale={locale} messages={messages}>
                <Providers>
                    {children}
                </Providers>
            </NextIntlClientProvider>
        </body>
        </html>
    )
}
